services:
  - type: web
    name: youtube-downloader-backend
    env: python
    buildCommand: |
      chmod +x start.sh
      pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 10000
